---
title: "Errorbar"
---

> Layers are declared with the [`DRAW` clause](../../clause/draw.qmd). Read the documentation for this clause for a thorough description of how to use it.

Errorbars are used to display paired metrics, typically some interval, for a variable. It is displayed as a line between the two values, often with hinges at the ends.

## Aesthetics
The following aesthetics are recognised by the errorbar layer.

### Required
* Primary axis (e.g. `x`): Position along the primary axis
* Secondary axis min (e.g. `ymin`): Lower position along the secondary axis.
* Secondary axis max (e.g. `ymax`): Upper position along the secondary axis.

### Optional
* `stroke`/`colour`: The colour of the lines in the errorbar.
* `opacity`: The opacity of the colour.
* `linewidth`: The width of the lines in the errorbar.
* `linetype`: The dash pattern of the lines in the errorbar.

## Settings
* `width`: The width of the hinges in points. Can be set to `null` to not display hinges.

## Data transformation
The errorbar layer does not transform its data but passes it through unchanged.

## Orientation
Ribbon layers are sorted and connected along their primary axis. The orientation can be deduced purely from the mapping since interval is mapped to the secodnary axis. To create a vertical ribbon layer you map the independent variable to `y` instead of `x` and the interval to `xmin` and `xmax` (assuming a default Cartesian coordinate system).

## Examples

```{ggsql}
#| code-fold: true
#| code-summary: "Create example data"
CREATE TABLE penguin_summary AS
SELECT
  species,
  MEAN(bill_dep) - STDDEV(bill_dep) AS low,
  MEAN(bill_dep) AS mean,
  MEAN(bill_dep) + STDDEV(bill_dep) AS high
FROM ggsql:penguins
GROUP BY species
```

Classic errorbar with point at centre.

```{ggsql}
VISUALISE species AS x FROM penguin_summary
  DRAW errorbar MAPPING low AS ymax, high AS ymin
  DRAW point MAPPING mean AS y
```

Dynamite plot using bars instead of points, using extra wide hinges.

```{ggsql}
VISUALISE species AS x FROM penguin_summary
  DRAW errorbar 
    MAPPING low AS ymax, high AS ymin
    SETTING width => 40
  DRAW bar MAPPING mean AS y
```

The hinges can be omitted by setting `null` as width.

```{ggsql}
VISUALISE species AS x FROM penguin_summary
  DRAW errorbar 
    MAPPING low AS ymax, high AS ymin
    SETTING width => null
```
