---
title: "Line"
---

> Layers are declared with the [`DRAW` clause](../../clause/draw.qmd). Read the documentation for this clause for a thorough description of how to use it.

The line layer is used to create lineplots. Lineplots always connects records along the x-axis, in contrast to [path layers](path.qmd) which use the order of data to connect records. Lines are divided due to their grouping, which is the combination of the discrete mapped aesthetics and the columns specified in the layers [`PARTITION BY`](../../clause/draw.qmd#partition-by).

## Aesthetics
The following aesthetics are recognised by the line layer.

### Required
* Primary axis (e.g. `x`): The value of the independent variable.
* Secondary axis (e.g. `y`): The value of the dependent variable.

### Optional
* `colour`/`stroke`: The colour of the line
* `opacity`: The opacity of the line
* `linewidth`: The width of the line
* `linetype`: The type of line, i.e. the dashing pattern

## Settings
* `position`: Position adjustment. One of `'identity'` (default), `'stack'`, `'dodge'`, or `'jitter'`
* `orientation`: The orientation of the layer, see the [Orientation section](#orientation). One of the following:
    * `'aligned'` to align the layer's primary axis with the coordinate system's first axis.
    * `'transposed'` to align the layer's primary axis with the coordinate system's second axis.

## Data transformation
The line layer sorts the data along its primary axis.

## Orientation
Line plots are sorted and connected along their primary axis. Since the primary axis cannot be deduced from the mapping it must be specified using the `orientation` setting. If you wish to create a vertical line plot, you need to set `orientation => 'transposed'` to indicate that the primary layer axis follows the second axis of the coordinate system.  

## Examples

Standard lineplot

```{ggsql}
VISUALISE FROM ggsql:airquality
DRAW line
  MAPPING Date AS x, Temp AS y
```

Use `PARTITION BY` to create multiple lines

```{ggsql}
VISUALISE FROM ggsql:airquality
DRAW line
  MAPPING Day AS x, Temp AS y
  PARTITION BY Month
```

or split them with an aesthetic

```{ggsql}
VISUALISE FROM ggsql:airquality
DRAW line
  MAPPING Day AS x, Temp AS y, Month AS color
```
