-- case: scatter_color
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_fill__", "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__", "grp" AS "__ggsql_aes_stroke__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "grp" AS "__ggsql_aes_fill__", "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__", "grp" AS "__ggsql_aes_stroke__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__";

-- case: histogram
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "val" AS "__ggsql_aes_pos1__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT MIN("__ggsql_aes_pos1__") as min_val, MAX("__ggsql_aes_pos1__") as max_val FROM (SELECT *, "val" AS "__ggsql_aes_pos1__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_stats__";
SELECT *, "__ggsql_stat_bin" AS "__ggsql_aes_pos1__", "__ggsql_stat_bin_end" AS "__ggsql_aes_pos1end__", "__ggsql_stat_count" AS "__ggsql_aes_pos2__" FROM (WITH "__stat_src__" AS (SELECT *, "val" AS "__ggsql_aes_pos1__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__"), "__bin_src__" AS (SELECT *, (GREATEST(0, CEIL(("__ggsql_aes_pos1__" - 1 + 1 * 0.5) / 1) - 1)) * 1 + 1 - 1 * 0.5 AS "__ggsql_bin_key__" FROM "__stat_src__"), "__binned__" AS (SELECT "__ggsql_bin_key__" AS "__ggsql_stat_bin", COUNT(*) AS "__ggsql_stat_count" FROM "__bin_src__" GROUP BY "__ggsql_bin_key__") SELECT *, "__ggsql_stat_bin" + 1 AS "__ggsql_stat_bin_end", "__ggsql_stat_count" * 1.0 / SUM("__ggsql_stat_count") OVER () AS "__ggsql_stat_density" FROM "__binned__") AS "__ggsql_stat__";

-- case: boxplot_grouped
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_type" AS "__ggsql_aes_type__", "__ggsql_stat_value" AS "__ggsql_aes_pos2__", "__ggsql_stat_value2" AS "__ggsql_aes_pos2end__" FROM (WITH summary AS ( SELECT *, GREATEST(q1 - 1.5 * (q3 - q1), min) AS lower, LEAST(q3 + 1.5 * (q3 - q1), max) AS upper FROM (SELECT "__ggsql_aes_pos1__", MIN("__ggsql_aes_pos2__") AS min, MAX("__ggsql_aes_pos2__") AS max, APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.25) AS q1, APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.5) AS median, APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.75) AS q3 FROM (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_qt__" WHERE "__ggsql_aes_pos2__" IS NOT NULL GROUP BY "__ggsql_aes_pos1__") AS "__ggsql_fn__" ), outliers AS ( SELECT raw."__ggsql_aes_pos2__" AS value, 'outlier' AS type, raw."__ggsql_aes_pos1__" AS "__ggsql_aes_pos1__" FROM (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "raw" JOIN summary ON raw."__ggsql_aes_pos1__" = summary."__ggsql_aes_pos1__" WHERE raw."__ggsql_aes_pos2__" NOT BETWEEN summary.lower AND summary.upper ) SELECT "__ggsql_aes_pos1__", 'lower_whisker' AS "__ggsql_stat_type", q1 AS "__ggsql_stat_value", lower AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", 'upper_whisker' AS "__ggsql_stat_type", q3 AS "__ggsql_stat_value", upper AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", 'box' AS "__ggsql_stat_type", q1 AS "__ggsql_stat_value", q3 AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", 'median' AS "__ggsql_stat_type", median AS "__ggsql_stat_value", NULL AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", type AS "__ggsql_stat_type", value AS "__ggsql_stat_value", NULL AS "__ggsql_stat_value2" FROM outliers) AS "__ggsql_stat__";

-- case: line_aggregate
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_pos2" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM (WITH "__ggsql_stat_src__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT "__ggsql_aes_pos1__", AVG("__ggsql_aes_pos2__") AS "__ggsql_stat_pos2" FROM "__ggsql_stat_src__" AS "__ggsql_qt__" GROUP BY "__ggsql_aes_pos1__") AS "__ggsql_ord__" ORDER BY "__ggsql_aes_pos1__") AS "__ggsql_stat__";

-- case: density_grouped
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_fill__", "val" AS "__ggsql_aes_pos1__", "grp" AS "__ggsql_aes_stroke__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_pos1" AS "__ggsql_aes_pos1__", "__ggsql_stat_density" AS "__ggsql_aes_pos2__" FROM (WITH RECURSIVE bandwidth AS ( SELECT 0.9 * LEAST(SQRT(AVG("__ggsql_aes_pos1__"*"__ggsql_aes_pos1__") - AVG("__ggsql_aes_pos1__")*AVG("__ggsql_aes_pos1__")), (APPROX_PERCENTILE("__ggsql_aes_pos1__", 0.75) - APPROX_PERCENTILE("__ggsql_aes_pos1__", 0.25)) / 1.34) * POWER(1.0 * COUNT(*), -0.2) AS bw, "__ggsql_aes_fill__", "__ggsql_aes_stroke__", MIN("__ggsql_aes_pos1__") AS x_min, MAX("__ggsql_aes_pos1__") AS x_max FROM (SELECT *, "grp" AS "__ggsql_aes_fill__", "val" AS "__ggsql_aes_pos1__", "grp" AS "__ggsql_aes_stroke__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_qt__" WHERE "__ggsql_aes_pos1__" IS NOT NULL GROUP BY "__ggsql_aes_fill__", "__ggsql_aes_stroke__" ), data AS ( SELECT "__ggsql_aes_fill__", "__ggsql_aes_stroke__", "__ggsql_aes_pos1__" AS val, 1.0 AS weight FROM (SELECT *, "grp" AS "__ggsql_aes_fill__", "val" AS "__ggsql_aes_pos1__", "grp" AS "__ggsql_aes_stroke__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_data__" WHERE "__ggsql_aes_pos1__" IS NOT NULL ), "__ggsql_seq__"(n) AS (SELECT SEQ4()::FLOAT AS n FROM TABLE(GENERATOR(ROWCOUNT => 512))), global_range AS ( SELECT MIN(x_min) AS min, MAX(x_max) AS max, 3 * MAX(bw) AS expansion FROM bandwidth ), grid AS ( SELECT "__ggsql_aes_fill__", "__ggsql_aes_stroke__", ("__ggsql_global__".min - "__ggsql_global__".expansion) + (seq.n * (("__ggsql_global__".max - "__ggsql_global__".min) + 2 * "__ggsql_global__".expansion) / 511) AS x FROM global_range AS "__ggsql_global__" CROSS JOIN "__ggsql_seq__" AS seq CROSS JOIN (SELECT DISTINCT "__ggsql_aes_fill__", "__ggsql_aes_stroke__" FROM bandwidth) AS "__ggsql_groups__" ) SELECT "__ggsql_stat_pos1", "__ggsql_aes_fill__", "__ggsql_aes_stroke__", "__ggsql_stat_intensity", "__ggsql_stat_intensity" / "__norm" AS "__ggsql_stat_density" FROM ( SELECT grid.x AS "__ggsql_stat_pos1", grid."__ggsql_aes_fill__" AS "__ggsql_aes_fill__", grid."__ggsql_aes_stroke__" AS "__ggsql_aes_stroke__", SUM(data.weight * ((EXP(-0.5 * (grid.x - data.val) * (grid.x - data.val) / (bandwidth.bw * bandwidth.bw))) * 0.3989422804014327)) / MIN(bandwidth.bw) AS "__ggsql_stat_intensity", SUM(data.weight) AS "__norm" FROM data INNER JOIN bandwidth ON (data."__ggsql_aes_fill__" IS NOT DISTINCT FROM bandwidth."__ggsql_aes_fill__") AND (data."__ggsql_aes_stroke__" IS NOT DISTINCT FROM bandwidth."__ggsql_aes_stroke__") INNER JOIN grid ON (grid."__ggsql_aes_fill__" IS NOT DISTINCT FROM data."__ggsql_aes_fill__") AND (grid."__ggsql_aes_stroke__" IS NOT DISTINCT FROM data."__ggsql_aes_stroke__") GROUP BY grid.x, grid."__ggsql_aes_fill__", grid."__ggsql_aes_stroke__" ) AS "__ggsql_kde__") AS "__ggsql_stat__";

-- case: line_temporal
DROP TABLE IF EXISTS "__ggsql_global_<session>__";
CREATE TEMP TABLE "__ggsql_global_<session>__" AS SELECT * FROM ggsql_live_test;
SELECT * FROM (SELECT * FROM "__ggsql_global_<session>__") AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "day" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM "__ggsql_global_<session>__") AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "day" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM "__ggsql_global_<session>__") AS "__ggsql_src__" ORDER BY "__ggsql_aes_pos1__";

-- case: boxplot_global_source
DROP TABLE IF EXISTS "__ggsql_global_<session>__";
CREATE TEMP TABLE "__ggsql_global_<session>__" AS SELECT * FROM ggsql_live_test;
SELECT * FROM (SELECT * FROM "__ggsql_global_<session>__") AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM "__ggsql_global_<session>__") AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_type" AS "__ggsql_aes_type__", "__ggsql_stat_value" AS "__ggsql_aes_pos2__", "__ggsql_stat_value2" AS "__ggsql_aes_pos2end__" FROM (WITH summary AS ( SELECT *, GREATEST(q1 - 1.5 * (q3 - q1), min) AS lower, LEAST(q3 + 1.5 * (q3 - q1), max) AS upper FROM (SELECT "__ggsql_aes_pos1__", MIN("__ggsql_aes_pos2__") AS min, MAX("__ggsql_aes_pos2__") AS max, APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.25) AS q1, APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.5) AS median, APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.75) AS q3 FROM (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM "__ggsql_global_<session>__") AS "__ggsql_src__") AS "__ggsql_qt__" WHERE "__ggsql_aes_pos2__" IS NOT NULL GROUP BY "__ggsql_aes_pos1__") AS "__ggsql_fn__" ), outliers AS ( SELECT raw."__ggsql_aes_pos2__" AS value, 'outlier' AS type, raw."__ggsql_aes_pos1__" AS "__ggsql_aes_pos1__" FROM (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM "__ggsql_global_<session>__") AS "__ggsql_src__") AS "raw" JOIN summary ON raw."__ggsql_aes_pos1__" = summary."__ggsql_aes_pos1__" WHERE raw."__ggsql_aes_pos2__" NOT BETWEEN summary.lower AND summary.upper ) SELECT "__ggsql_aes_pos1__", 'lower_whisker' AS "__ggsql_stat_type", q1 AS "__ggsql_stat_value", lower AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", 'upper_whisker' AS "__ggsql_stat_type", q3 AS "__ggsql_stat_value", upper AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", 'box' AS "__ggsql_stat_type", q1 AS "__ggsql_stat_value", q3 AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", 'median' AS "__ggsql_stat_type", median AS "__ggsql_stat_value", NULL AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", type AS "__ggsql_stat_type", value AS "__ggsql_stat_value", NULL AS "__ggsql_stat_value2" FROM outliers) AS "__ggsql_stat__";

-- case: bar_count
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_count" AS "__ggsql_aes_pos2__" FROM (WITH "__stat_src__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__"), "__grouped__" AS (SELECT "__ggsql_aes_pos1__", COUNT(*) AS "__ggsql_stat_count" FROM "__stat_src__" GROUP BY "__ggsql_aes_pos1__") SELECT *, "__ggsql_stat_count" * 1.0 / SUM("__ggsql_stat_count") OVER () AS "__ggsql_stat_proportion" FROM "__grouped__") AS "__ggsql_stat__";

-- case: smooth_lm
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_pos1" AS "__ggsql_aes_pos1__", "__ggsql_stat_intensity" AS "__ggsql_aes_pos2__" FROM (WITH coefficients AS ( SELECT AVG("__ggsql_aes_pos1__") AS x_mean, AVG("__ggsql_aes_pos2__") AS y_mean, AVG("__ggsql_aes_pos1__" * "__ggsql_aes_pos2__") AS xy_mean, AVG("__ggsql_aes_pos1__" * "__ggsql_aes_pos1__") AS xx_mean, MIN("__ggsql_aes_pos1__") AS x_min, MAX("__ggsql_aes_pos1__") AS x_max FROM (SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_smooth__" WHERE "__ggsql_aes_pos1__" IS NOT NULL AND "__ggsql_aes_pos2__" IS NOT NULL ) SELECT x_min AS "__ggsql_stat_pos1", (y_mean + ((xy_mean - x_mean * y_mean) / (xx_mean - x_mean * x_mean)) * (x_min - x_mean)) AS "__ggsql_stat_intensity" FROM coefficients UNION ALL SELECT x_max AS "__ggsql_stat_pos1", (y_mean + ((xy_mean - x_mean * y_mean) / (xx_mean - x_mean * x_mean)) * (x_max - x_mean)) AS "__ggsql_stat_intensity" FROM coefficients) AS "__ggsql_stat__";

-- case: ribbon
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2max__", "id" AS "__ggsql_aes_pos2min__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2max__", "id" AS "__ggsql_aes_pos2min__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__" ORDER BY "__ggsql_aes_pos1__";

-- case: segment
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "id" AS "__ggsql_aes_pos1__", "id" AS "__ggsql_aes_pos1end__", "val" AS "__ggsql_aes_pos2__", "val" AS "__ggsql_aes_pos2end__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "id" AS "__ggsql_aes_pos1__", "id" AS "__ggsql_aes_pos1end__", "val" AS "__ggsql_aes_pos2__", "val" AS "__ggsql_aes_pos2end__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__";

-- case: tile
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "val" AS "__ggsql_aes_pos1__", "id" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_pos1min" AS "__ggsql_aes_pos1min__", "__ggsql_stat_pos1max" AS "__ggsql_aes_pos1max__", "__ggsql_stat_pos2min" AS "__ggsql_aes_pos2min__", "__ggsql_stat_pos2max" AS "__ggsql_aes_pos2max__" FROM (SELECT ("__ggsql_aes_pos1__" - 0.5) AS "__ggsql_stat_pos1min", ("__ggsql_aes_pos1__" + 0.5) AS "__ggsql_stat_pos1max", ("__ggsql_aes_pos2__" - 0.5) AS "__ggsql_stat_pos2min", ("__ggsql_aes_pos2__" + 0.5) AS "__ggsql_stat_pos2max" FROM (SELECT *, "val" AS "__ggsql_aes_pos1__", "id" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_tile_stat__") AS "__ggsql_stat__";

-- case: area
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__" ORDER BY "__ggsql_aes_pos1__";

-- case: violin
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_pos2" AS "__ggsql_aes_pos2__", "__ggsql_stat_density" AS "__ggsql_aes_offset__" FROM (WITH RECURSIVE bandwidth AS ( SELECT 0.9 * LEAST(SQRT(AVG("__ggsql_aes_pos2__"*"__ggsql_aes_pos2__") - AVG("__ggsql_aes_pos2__")*AVG("__ggsql_aes_pos2__")), (APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.75) - APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.25)) / 1.34) * POWER(1.0 * COUNT(*), -0.2) AS bw, "__ggsql_aes_pos1__", MIN("__ggsql_aes_pos2__") AS x_min, MAX("__ggsql_aes_pos2__") AS x_max FROM (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_qt__" WHERE "__ggsql_aes_pos2__" IS NOT NULL GROUP BY "__ggsql_aes_pos1__" ), data AS ( SELECT "__ggsql_aes_pos1__", "__ggsql_aes_pos2__" AS val, 1.0 AS weight FROM (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_data__" WHERE "__ggsql_aes_pos2__" IS NOT NULL ), "__ggsql_seq__"(n) AS (SELECT SEQ4()::FLOAT AS n FROM TABLE(GENERATOR(ROWCOUNT => 512))), global_range AS ( SELECT MIN(x_min) AS min, MAX(x_max) AS max, 3 * MAX(bw) AS expansion FROM bandwidth ), full_grid AS ( SELECT "__ggsql_aes_pos1__", ("__ggsql_global__".min - "__ggsql_global__".expansion) + (seq.n * (("__ggsql_global__".max - "__ggsql_global__".min) + 2 * "__ggsql_global__".expansion) / 511) AS x FROM global_range AS "__ggsql_global__" CROSS JOIN "__ggsql_seq__" AS seq CROSS JOIN (SELECT DISTINCT "__ggsql_aes_pos1__" FROM bandwidth) AS "__ggsql_groups__" ), grid AS ( SELECT full_grid."__ggsql_aes_pos1__" AS "__ggsql_aes_pos1__", full_grid.x FROM full_grid INNER JOIN bandwidth ON (full_grid."__ggsql_aes_pos1__" IS NOT DISTINCT FROM bandwidth."__ggsql_aes_pos1__") WHERE full_grid.x >= bandwidth.x_min - 3 * bandwidth.bw AND full_grid.x <= bandwidth.x_max + 3 * bandwidth.bw ) SELECT "__ggsql_stat_pos2", "__ggsql_aes_pos1__", "__ggsql_stat_intensity", "__ggsql_stat_intensity" / "__norm" AS "__ggsql_stat_density" FROM ( SELECT grid.x AS "__ggsql_stat_pos2", grid."__ggsql_aes_pos1__" AS "__ggsql_aes_pos1__", SUM(data.weight * ((EXP(-0.5 * (grid.x - data.val) * (grid.x - data.val) / (bandwidth.bw * bandwidth.bw))) * 0.3989422804014327)) / MIN(bandwidth.bw) AS "__ggsql_stat_intensity", SUM(data.weight) AS "__norm" FROM data INNER JOIN bandwidth ON (data."__ggsql_aes_pos1__" IS NOT DISTINCT FROM bandwidth."__ggsql_aes_pos1__") INNER JOIN grid ON (grid."__ggsql_aes_pos1__" IS NOT DISTINCT FROM data."__ggsql_aes_pos1__") GROUP BY grid.x, grid."__ggsql_aes_pos1__" ) AS "__ggsql_kde__") AS "__ggsql_stat__";

-- case: filter_layer
DROP TABLE IF EXISTS "__ggsql_global_<session>__";
CREATE TEMP TABLE "__ggsql_global_<session>__" AS SELECT * FROM ggsql_live_test;
SELECT * FROM (SELECT * FROM "__ggsql_global_<session>__") AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM "__ggsql_global_<session>__") AS "__ggsql_src__" WHERE grp = 'a') SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM "__ggsql_global_<session>__") AS "__ggsql_src__" WHERE grp = 'a';

-- case: binned_temporal
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "day" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT "id", "val", "grp", "day", "mixed Case", (CASE WHEN TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) >= 19000 AND TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) < 19000.2 THEN 19000.1 WHEN TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) >= 19000.2 AND TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) < 19000.4 THEN 19000.300000000003 WHEN TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) >= 19000.4 AND TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) < 19000.6 THEN 19000.5 WHEN TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) >= 19000.6 AND TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) < 19000.8 THEN 19000.699999999997 WHEN TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) >= 19000.8 AND TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) < 19001 THEN 19000.9 WHEN TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) >= 19001 AND TRY_CAST("__ggsql_aes_pos1__" AS DOUBLE) <= 19001.2 THEN 19001.1 ELSE NULL END) AS "__ggsql_aes_pos1__", "__ggsql_aes_pos2__" FROM (SELECT *, "day" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_pre__";

-- case: binned_temporal_date
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "day" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT "id", "val", "grp", "day", "mixed Case", (CASE WHEN "__ggsql_aes_pos1__" >= CAST('2022-01-08' AS DATE) AND "__ggsql_aes_pos1__" <= CAST('2022-01-09' AS DATE) THEN CAST('2022-01-08' AS DATE) ELSE NULL END) AS "__ggsql_aes_pos1__", "__ggsql_aes_pos2__" FROM (SELECT *, "day" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_pre__";

-- case: sum_aggregate
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_pos2" AS "__ggsql_aes_pos2__" FROM (WITH "__ggsql_stat_src__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT "__ggsql_aes_pos1__", SUM("__ggsql_aes_pos2__") AS "__ggsql_stat_pos2" FROM "__ggsql_stat_src__" AS "__ggsql_qt__" GROUP BY "__ggsql_aes_pos1__") AS "__ggsql_stat__";

-- case: percentile_p10
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__" WHERE grp = 'a') SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_pos2" AS "__ggsql_aes_pos2__" FROM (WITH "__ggsql_stat_src__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__" WHERE grp = 'a') SELECT "__ggsql_aes_pos1__", APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.1) AS "__ggsql_stat_pos2" FROM "__ggsql_stat_src__" AS "__ggsql_qt__" GROUP BY "__ggsql_aes_pos1__") AS "__ggsql_stat__";

-- case: percentile_p90
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__" WHERE grp = 'a') SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_pos2" AS "__ggsql_aes_pos2__" FROM (WITH "__ggsql_stat_src__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__" WHERE grp = 'a') SELECT "__ggsql_aes_pos1__", APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.9) AS "__ggsql_stat_pos2" FROM "__ggsql_stat_src__" AS "__ggsql_qt__" GROUP BY "__ggsql_aes_pos1__") AS "__ggsql_stat__";

-- case: quoted_column
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_pos1__", "mixed Case" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_type" AS "__ggsql_aes_type__", "__ggsql_stat_value" AS "__ggsql_aes_pos2__", "__ggsql_stat_value2" AS "__ggsql_aes_pos2end__" FROM (WITH summary AS ( SELECT *, GREATEST(q1 - 1.5 * (q3 - q1), min) AS lower, LEAST(q3 + 1.5 * (q3 - q1), max) AS upper FROM (SELECT "__ggsql_aes_pos1__", MIN("__ggsql_aes_pos2__") AS min, MAX("__ggsql_aes_pos2__") AS max, APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.25) AS q1, APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.5) AS median, APPROX_PERCENTILE("__ggsql_aes_pos2__", 0.75) AS q3 FROM (SELECT *, "grp" AS "__ggsql_aes_pos1__", "mixed Case" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_qt__" WHERE "__ggsql_aes_pos2__" IS NOT NULL GROUP BY "__ggsql_aes_pos1__") AS "__ggsql_fn__" ), outliers AS ( SELECT raw."__ggsql_aes_pos2__" AS value, 'outlier' AS type, raw."__ggsql_aes_pos1__" AS "__ggsql_aes_pos1__" FROM (SELECT *, "grp" AS "__ggsql_aes_pos1__", "mixed Case" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "raw" JOIN summary ON raw."__ggsql_aes_pos1__" = summary."__ggsql_aes_pos1__" WHERE raw."__ggsql_aes_pos2__" NOT BETWEEN summary.lower AND summary.upper ) SELECT "__ggsql_aes_pos1__", 'lower_whisker' AS "__ggsql_stat_type", q1 AS "__ggsql_stat_value", lower AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", 'upper_whisker' AS "__ggsql_stat_type", q3 AS "__ggsql_stat_value", upper AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", 'box' AS "__ggsql_stat_type", q1 AS "__ggsql_stat_value", q3 AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", 'median' AS "__ggsql_stat_type", median AS "__ggsql_stat_value", NULL AS "__ggsql_stat_value2" FROM summary UNION ALL SELECT "__ggsql_aes_pos1__", type AS "__ggsql_stat_type", value AS "__ggsql_stat_value", NULL AS "__ggsql_stat_value2" FROM outliers) AS "__ggsql_stat__";

-- case: partition_by_quoted
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "id" AS "__ggsql_aes_pos1__", "mixed Case" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_pos2" AS "__ggsql_aes_pos2__" FROM (WITH "__ggsql_stat_src__" AS (SELECT *, "id" AS "__ggsql_aes_pos1__", "mixed Case" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT "mixed Case", AVG("__ggsql_aes_pos2__") AS "__ggsql_stat_pos2" FROM "__ggsql_stat_src__" AS "__ggsql_qt__" GROUP BY "mixed Case") AS "__ggsql_stat__";

-- case: grouped_bar
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_fill__", "grp" AS "__ggsql_aes_pos1__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_count" AS "__ggsql_aes_pos2__" FROM (WITH "__stat_src__" AS (SELECT *, "grp" AS "__ggsql_aes_fill__", "grp" AS "__ggsql_aes_pos1__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__"), "__grouped__" AS (SELECT "__ggsql_aes_fill__", "__ggsql_aes_pos1__", COUNT(*) AS "__ggsql_stat_count" FROM "__stat_src__" GROUP BY __ggsql_aes_fill__, "__ggsql_aes_pos1__") SELECT *, "__ggsql_stat_count" * 1.0 / SUM("__ggsql_stat_count") OVER (PARTITION BY "__ggsql_aes_fill__") AS "__ggsql_stat_proportion" FROM "__grouped__") AS "__ggsql_stat__";

-- case: grouped_histogram
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "grp" AS "__ggsql_aes_fill__", "val" AS "__ggsql_aes_pos1__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT MIN("__ggsql_aes_pos1__") as min_val, MAX("__ggsql_aes_pos1__") as max_val FROM (SELECT *, "grp" AS "__ggsql_aes_fill__", "val" AS "__ggsql_aes_pos1__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_stats__";
SELECT *, "__ggsql_stat_bin" AS "__ggsql_aes_pos1__", "__ggsql_stat_bin_end" AS "__ggsql_aes_pos1end__", "__ggsql_stat_count" AS "__ggsql_aes_pos2__" FROM (WITH "__stat_src__" AS (SELECT *, "grp" AS "__ggsql_aes_fill__", "val" AS "__ggsql_aes_pos1__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__"), "__bin_src__" AS (SELECT *, (GREATEST(0, CEIL(("__ggsql_aes_pos1__" - 1 + 1 * 0.5) / 1) - 1)) * 1 + 1 - 1 * 0.5 AS "__ggsql_bin_key__" FROM "__stat_src__"), "__binned__" AS (SELECT "__ggsql_aes_fill__", "__ggsql_bin_key__" AS "__ggsql_stat_bin", COUNT(*) AS "__ggsql_stat_count" FROM "__bin_src__" GROUP BY __ggsql_aes_fill__, "__ggsql_bin_key__") SELECT *, "__ggsql_stat_bin" + 1 AS "__ggsql_stat_bin_end", "__ggsql_stat_count" * 1.0 / SUM("__ggsql_stat_count") OVER (PARTITION BY "__ggsql_aes_fill__") AS "__ggsql_stat_density" FROM "__binned__") AS "__ggsql_stat__";

-- case: grouped_smooth
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__", "grp" AS "__ggsql_aes_stroke__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "__ggsql_stat_pos1" AS "__ggsql_aes_pos1__", "__ggsql_stat_intensity" AS "__ggsql_aes_pos2__" FROM (WITH coefficients AS ( SELECT "__ggsql_aes_stroke__", AVG("__ggsql_aes_pos1__") AS x_mean, AVG("__ggsql_aes_pos2__") AS y_mean, AVG("__ggsql_aes_pos1__" * "__ggsql_aes_pos2__") AS xy_mean, AVG("__ggsql_aes_pos1__" * "__ggsql_aes_pos1__") AS xx_mean, MIN("__ggsql_aes_pos1__") AS x_min, MAX("__ggsql_aes_pos1__") AS x_max FROM (SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__", "grp" AS "__ggsql_aes_stroke__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_smooth__" WHERE "__ggsql_aes_pos1__" IS NOT NULL AND "__ggsql_aes_pos2__" IS NOT NULL GROUP BY "__ggsql_aes_stroke__" ) SELECT "__ggsql_aes_stroke__", x_min AS "__ggsql_stat_pos1", (y_mean + ((xy_mean - x_mean * y_mean) / (xx_mean - x_mean * x_mean)) * (x_min - x_mean)) AS "__ggsql_stat_intensity" FROM coefficients UNION ALL SELECT "__ggsql_aes_stroke__", x_max AS "__ggsql_stat_pos1", (y_mean + ((xy_mean - x_mean * y_mean) / (xx_mean - x_mean * x_mean)) * (x_max - x_mean)) AS "__ggsql_stat_intensity" FROM coefficients) AS "__ggsql_stat__";

-- case: spatial_mercator
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT proj4text FROM spatial_ref_sys WHERE srid = 4326 LIMIT 1;
SELECT ST_Transform(ST_SetSRID(ST_Point(0, 0), 4326), '+proj=merc +lon_0=0') AS g;
DROP TABLE IF EXISTS "__ggsql_clip_boundary_<session>__";
CREATE TEMP TABLE "__ggsql_clip_boundary_<session>__" AS SELECT ST_Transform(ST_SetSRID(ST_GeomFromText('POLYGON((-180.000000 85.000000, 180.000000 85.000000, 180.000000 -85.000000, -180.000000 -85.000000, -180.000000 85.000000))'), 4326), '+proj=longlat +datum=WGS84 +no_defs +type=crs') AS geom;
SELECT ST_AsText(ST_Transform(ST_SetSRID(ST_GeomFromText('POLYGON((-180.000000 85.000000, 180.000000 85.000000, 180.000000 -85.000000, -180.000000 -85.000000, -180.000000 85.000000))'), 4326), '+proj=merc +lon_0=0')) AS wkt;
SELECT MIN(ST_XMIN(g)) AS xmin, MIN(ST_YMIN(g)) AS ymin, MAX(ST_XMAX(g)) AS xmax, MAX(ST_YMAX(g)) AS ymax FROM (SELECT ST_ENVELOPE(ST_Transform(ST_SetSRID(geom, 4326), '+proj=merc +lon_0=0')) AS g FROM __ggsql_clip_boundary_<session>__);
DROP TABLE IF EXISTS "__ggsql_layer_0___proj";
CREATE TEMP TABLE "__ggsql_layer_0___proj" AS SELECT ST_X("__ggsql_proj_pt__") AS "__ggsql_aes_pos1__", ST_Y("__ggsql_proj_pt__") AS "__ggsql_aes_pos2__" FROM (SELECT *, ST_Transform(ST_SetSRID(ST_Point("__ggsql_aes_pos1__", "__ggsql_aes_pos2__"), 4326), '+proj=merc +lon_0=0') AS "__ggsql_proj_pt__" FROM (SELECT *, "id" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") AS "__ggsql_proj__") AS "__ggsql_pp__";
SELECT MIN("__ggsql_aes_pos1__"), MIN("__ggsql_aes_pos2__"), MAX("__ggsql_aes_pos1__"), MAX("__ggsql_aes_pos2__") FROM "__ggsql_layer_0___proj";
SELECT * FROM "__ggsql_layer_0___proj";

-- case: text_date_cast
SELECT * FROM (SELECT * FROM ggsql_live_test) AS "__schema__" LIMIT 1;
WITH "__ggsql_source__" AS (SELECT *, "day" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__") SELECT MIN("id") AS "id", MAX("id") AS "__ggsql_max_id", MIN("val") AS "val", MAX("val") AS "__ggsql_max_val", MIN("grp") AS "grp", MAX("grp") AS "__ggsql_max_grp", MIN("day") AS "day", MAX("day") AS "__ggsql_max_day", MIN("mixed Case") AS "mixed Case", MAX("mixed Case") AS "__ggsql_max_mixed Case" FROM "__ggsql_source__";
SELECT *, "day" AS "__ggsql_aes_pos1__", "val" AS "__ggsql_aes_pos2__" FROM (SELECT * FROM ggsql_live_test) AS "__ggsql_src__";

